#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          15

bspc config active_border_color	"#04A5E5"
bspc config focused_border_color	"#D23D3D"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sh ~/.config/polybar/launch.sh
nitrogen --restore
setxkbmap -model pc105 -layout us,ru -option grp:alt_shift_toggle
picom -b --backend glx

xinput set-prop 10 "libinput Accel Profile Enabled" 0 1 0
xinput set-prop 10 'libinput Accel Speed' -0.45
xinput set-prop "ASUE1A00:00 04F3:31DE Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ASUE1A00:00 04F3:31DE Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "ASUE1A00:00 04F3:31DE Touchpad" "libinput Disable While Typing Enabled" 0
